CONFIG_USB_DEVICE_STACK_NEXT=y

CONFIG_STDOUT_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_UART_LINE_CTRL=y
CONFIG_USBD_CDC_ACM_CLASS=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=n

CONFIG_LOG=y
CONFIG_USBD_LOG_LEVEL_ERR=y
CONFIG_UDC_DRIVER_LOG_LEVEL_DBG=y
CONFIG_USBD_CDC_ACM_LOG_LEVEL_DBG=y

CONFIG_SAMPLE_USBD_PID=0x0420
CONFIG_SAMPLE_USBD_PRODUCT="USBD my own CDC sample"

CONFIG_WATCHDOG=y

CONFIG_EARLY_CONSOLE=y
#CONFIG_WDT_TIMEOUT_MSEC=5000

#CONFIG_UDC_BUF_FORCE_NOCACHE=n
#CONFIG_DCACHE_LINE_SIZE_DETECT=n
#CONFIG_DCACHE_LINE_SIZE=64

CONFIG_REBOOT=y
CONFIG_SHELL=y
CONFIG_NOCACHE_MEMORY=n

CONFIG_THREAD_STACK_INFO=y
CONFIG_INIT_STACKS=y
CONFIG_STACK_SENTINEL=y
# If supported on your SoC:
CONFIG_HW_STACK_PROTECTION=y
CONFIG_UDC_WORKQUEUE_STACK_SIZE=8192
CONFIG_USBD_THREAD_STACK_SIZE=8192
CONFIG_USBD_CDC_ACM_WORKQUEUE=y
CONFIG_USBD_CDC_ACM_STACK_SIZE=8192